# Jekyll Configuration for Yazeid's Personal Website

title: "Yazeid's Personal Site"
description: "My personal website for blogs, projects, and contact"
markdown: kramdown
highlighter: rouge

# Development server config (ignored on GitHub Pages)
host: 127.0.0.1
port: 4000

# Blog URL structure
permalink: /blog/:year/:month/:title.html

# Site-wide settings
snow: 0
christmas: 0

# Plugins (jekyll-redirect-from must be installed locally)
plugins:
  - jekyll-redirect-from

# Custom collections (optional feature you're using)
collections:
  platforms:
    output: true

# Default values for blog posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      is_post: true


